### ISSUE TITLE
从网易到QQ同步失败

### ISSUE THREAD

**Issue by Removable** [Denon/syncPlaylist#4]
貌似是成功读取了网易云音乐的列表了，但是导入结果既没有成功数，也没用失败数，如下图
![如图](https://ooo.0o0.ooo/2017/07/12/5965ea83ae8ea.png)
请问大概是什么问题呢？谢谢

**Comment by Denon** [comment]
网易云音乐的歌单url发我看一下。。。 @Removable

**Comment by Removable** [comment]
@Denon 这个：[http://music.163.com/#/playlist?id=103133533&userid=89400120](http://music.163.com/#/playlist?id=103133533&userid=89400120)

**Comment by Denon** [comment]
@Removable 恩，手机页面html更改了，我换成从api获取应该会稳定点。

**Comment by Removable** [comment]
@Denon 好的，非常感谢

**Comment by Denon** [comment]
@Removable  已修复

**Comment by Removable** [comment]
@Denon 你好，现在一运行run.exe，就直接这样显示
![QQ图片20170714151608.png](https://i.loli.net/2017/07/14/59686fc450be0.png)
请问是什么原因

**Comment by Denon** [comment]
@Removable ...惊了， 应该是打包的时候出的问题， 我晚些回去再打包一次= =

**Comment by Removable** [comment]
@Denon 哈哈哈，好的

**Comment by Denon** [comment]
@Removable 这次应该好了。你试试

**Comment by Removable** [comment]
@Denon 现在一直登陆失败

![QQ截图20170714212720.png](https://i.loli.net/2017/07/14/5968c6fe565f7.png)

**Comment by Denon** [comment]
@奇怪，我这边没有这个问题。 你账号是写在 win32/dist/config.json 这里面的么

**Comment by Removable** [comment]
@Denon 你好，我今天在公司试了一下，能登陆成功了，不过好像同步还是不行

![QQ截图20170717092318.png](https://i.loli.net/2017/07/17/596c134a238ff.png)

**Comment by Denon** [comment]
嗯， 后面那个错是编码问题，我已经修复了，但是看上面的同步状态都是失败的。我试了一下在我电脑上同步你的歌单是成功的。有点奇怪。。。

不过你先更新试一下吧。
@Removable

**Comment by Removable** [comment]
对啊，一直是这样的
DaHong Wu <notifications@github.com>于2017年7月17日 周一22:21写道：

**Comment by demostars** [comment]
同样的错误

```
Traceback (most recent call last):
  File "run.py", line 27, in <module>
Exception: Please Download driver first!!!
Error! press Enter to exit

```

请问下如何处理呢？

参照上面回复是使用API方式了是么，API方式歌曲列表最多为1000，存在一个限制

感谢开发~

**Comment by Denon** [comment]
@demostars 对的，现在是用api的方式， 这个限制我还真没测试过

编码问题的话， 你这边是用python直接执行还是用exe来执行的？
