### ISSUE TITLE
 Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by willhunger** [Denon/syncPlaylist#6]
> login sucess
> Traceback (most recent call last):
>   File "base.pyc", line 76, in run
>   File "QQtoWY.pyc", line 38, in get_source_playlist
>   File "requests\api.pyc", line 72, in get
>   File "requests\api.pyc", line 58, in request
>   File "requests\sessions.pyc", line 502, in request
>   File "requests\sessions.pyc", line 612, in send
>   File "requests\adapters.pyc", line 407, in send
>   File "requests\adapters.pyc", line 226, in cert_verify
> IOError: Could not find a suitable TLS CA certificate bundle, invalid path: F:\syncPlaylist\dist\library.zip\certifi\cacert.pem
> total success:0
> total failed:0, detail:

**Comment by Denon** [comment]
在windows上? 试下用http的qq音乐地址. 这个应该是那个文件没有打包进去. 可能下个版本我会修复下。

**Comment by willhunger** [comment]
对的，在windows上，换成了http连接的话，程序完全卡在了选择1或者2的地方。
在Linux上跑不起来，因为你是py2写的，直接引入了urrlib2这个不存在的包，
然后我用py3，也是卡在了奇怪的地方

**Comment by Denon** [comment]
恩? windows上应该是好的。 你下的是最新的版本吗？ 我调整了顺序以后，应该是先获取歌单再登录的。现在我版本控制还做的不是很好，sorry。
至于在linux上的话，这个需要自己下载驱动。 urllib2这个包py2应该是有的。（不过linux上我还没测试过）
现在暂时还不支持py3

@willhunger

**Comment by willhunger** [comment]
多谢你啦
